GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS0lNIiwiaWF0IjoxNjUyMjM5MDIzLCJleHAiOjE2NTIyMzkwMzh9.6kDogHOZxIqkWC6foq1rcDmSNowej7SoRQDMevRZlXs

###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS0lNIiwiaWF0IjoxNjUyMjM5MDIzfQ.xz7qtFKG0fdkrmB-mkEoPXn0CHvHznrkhH1JKRklVFU"
}

###
POST http://localhost:4000/token
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS0lNIiwiaWF0IjoxNjUyMjM5MDIzfQ.xz7qtFKG0fdkrmB-mkEoPXn0CHvHznrkhH1JKRklVFU"
}

###
POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "KIM"
}